export const chapters = [
  { title: '01/05/2026', subtitle: '03:32', intro: 'Tudo começou em 01 de maio, às 03:32. Uma partida de Valorant que parecia comum, até você aparecer nela.', type: 'portrait', cards: [
    ['03:32, uma partida e você', 'Eu estava mais quieto, você estava fazendo o squad inteiro conversar. De repente o assunto virou Caim, Abel e perguntas da Bíblia. Foi aleatório, engraçado e impossível não lembrar de você.'], ['O convite que voltou', 'Depois daquela madrugada você me adicionou, chamou para jogar e chamou de novo. Sem perceber, cada convite virou mais uma chance de ficar perto.'], ['O acaso mais bonito', 'Eu não entrei naquela fila procurando alguma coisa. Mas tive a sorte de cair na mesma partida que você. E quatro meses depois, ainda agradeço por isso.'] ] },
  { title: 'Como tudo aconteceu?', subtitle: 'Jogo, call e presença', intro: 'Não foi de uma vez. Foi jogo depois de jogo, call depois de call, até você deixar de ser só uma companhia e virar parte dos meus dias.', type: 'timeline', cards: [
    ['Quando ainda era só jogo', 'No começo era Valorant, conversa atravessada e você puxando assunto com todo mundo. Só que, mesmo sem perceber, eu já esperava você aparecer.'], ['Quando eu quis estar perto', 'Em uma fase difícil sua, eu entendi que queria mais do que jogar junto. Queria te ouvir, te apoiar e deixar seus dias um pouco mais leves.'], ['Quando virou sentimento', 'Eu percebi no meio do trabalho, contando as horas para ligar o computador. Não era pelo jogo. Era pela vontade de conversar com você e ficar por perto.'] ] },
  { title: 'Coisas que são sua cara', subtitle: 'Detalhes que guardo', intro: 'Não existe um jeito de resumir você. Mas existem detalhes que, quando aparecem, sempre fazem eu pensar: isso é muito Maria.', type: 'details', cards: [
    ['26 de outubro', 'O dia em que nasceu alguém que deixa os dias de muita gente mais vivos. Eu só sou uma das pessoas que teve a sorte de perceber isso.'], ['O seu jeitinho', 'Você começa em um assunto, passa por outros dez e, no fim, transforma qualquer conversa em uma história boa. Eu gosto muito desse seu caos bonito.'], ['As suas frases', 'Você tem frases que ficam. Tem coragem, tem humor e tem esse jeito de lembrar todo mundo que Maria não segue a onda. A onda segue Maria.'], ['Seu kit oficial', 'Ursinhos, gatos, Golden Retriever, Doberman e Senhor dos Anéis. Coisas que parecem pequenas, mas que ajudam a desenhar quem você é para mim.'], ['Seu pedido perfeito', 'Sushi, hambúrguer, pizza, doce e um monte de opções. Eu gosto até de imaginar uma noite simples escolhendo tudo isso com você.'], ['O que eu mais noto', 'Seu sorriso, seus olhos, seu cabelo, suas reações. Você tem um jeito de transformar uma coisa comum em uma lembrança que eu quero guardar.'] ] },
  { title: 'Nossas noites', subtitle: 'GTA, call e carinho', intro: 'Teve uma semana em que GTA Online deixou de ser só um jogo. Virou cenário para risadas, conversa e uma intimidade que foi crescendo sem fazer barulho.', type: 'nights', cards: [['Uma semana que ficou', 'A gente jogou muito, riu muito e passou horas em call. Aos poucos, o que era rotina virou uma das partes mais gostosas dos meus dias.'], ['O primeiro “mô”', 'No meio das calls o “mô” apareceu. Depois vieram as primeiras noites dormindo juntos em ligação. Coisas pequenas para o mundo, mas enormes para mim.'], ['Os nossos “eu te amo”', 'Eu lembro do meu primeiro “eu te amo”. Lembro do seu também. Não preciso explicar muito, porque tem sentimento que fica guardado do jeito mais bonito.']] },
  { title: 'Músicas que são você', subtitle: 'O som de nós dois', intro: 'Algumas músicas você escolheu. Outras ganharam seu nome dentro de mim. Todas viraram uma forma de lembrar de nós quando a distância aperta.', type: 'music', cards: [['As que você trouxe', 'Músicas que chegaram com você e ficaram por aqui.'], ['As que agora são nossas', 'Músicas que fazem eu pensar em você antes mesmo de tocar o refrão.']] },
  { title: 'O que eu quero viver', subtitle: 'Depois dos quatro meses', intro: 'Eu não quero apressar o que é bonito. Quero continuar conhecendo você, cuidando do que temos e vivendo, sem medo, tudo o que ainda pode ser nosso.', type: 'future', cards: [['Do jeito que está sendo', 'Eu gosto das nossas conversas, dos desabafos, das zoeiras e até dos silêncios. Gosto de ter você fazendo parte do meu dia.'], ['Mais noites assim', 'Quero mais calls, mais jogos, mais “môs” e mais noites em que o melhor plano seja apenas ficar junto.']] },
  { title: 'Pra você', subtitle: 'O que quatro meses fizeram', intro: 'Guardei esta parte para o final porque é aqui que eu consigo te dizer o que toda essa história significa para mim.', type: 'letter', cards: [] }
];

function renderGallery() {
  return `<div class="gallery">${[['01','#e6b6b0','m','uma tarde bonita','-3deg'],['02','#c6adb2','M','entre risos','2deg'],['03','#dec4aa','✦','luz dourada','-1deg'],['04','#b7c7bf','m','sem pressa','3deg'],['05','#d4bbc4','♡','só nós','-2deg'],['06','#aebecb','M','um lugar feliz','3deg']].map(([id,tone,mark,title,tilt]) => `<button class="polaroid" style="--tone:${tone};--tilt:${tilt}" data-id="${id}" data-tone="${tone}" data-mark="${mark}" data-title="${title}" data-caption="Uma lembrança feita de detalhes, de tudo aquilo que não precisa ser explicado."><div class="photo-art"><span>${mark}</span></div><small>${title}</small></button>`).join('')}</div>`;
}

function renderMusic() {
  const tracks = [
    ['Te Encontrar', 'Modéstia Parte', 'assets/audio/te-encontrar.mp3', 56, 86, ['Quando essa música começa,', 'eu volto para aquela madrugada', 'em que eu ainda não sabia', 'o quanto você ia significar para mim.']],
    ['Linda, Louca e Mimada', 'Oriente', 'assets/audio/linda-louca-e-mimada.mp3', 72, 102, ['Você faz tudo do seu jeito.', 'Ninguém tem a sua energia.', 'E talvez seja exatamente por isso', 'que eu gosto tanto de você.']],
    ['Like I Want You', 'Giveon', 'assets/audio/like-i-want-you.mp3', 69, 99, ['Tem coisa que eu tento disfarçar.', 'Eu finjo que não penso tanto.', 'Mas depois de quatro meses,', 'meu coração sempre entrega você.']],
    ['Pupila', 'ANAVITÓRIA e Vitor Kley', 'assets/audio/pupila.mp3', 60, 90, ['Você aparece nos meus pensamentos.', 'No meio de qualquer dia comum.', 'E eu gosto até das partes do dia', 'em que eu paro só para lembrar de você.']],
    ['Meu Abrigo', 'Melim', 'assets/audio/meu-abrigo.mp3', 81, 111, ['Você é meu lugar de paz.', 'A minha escolha em dias leves e difíceis.', 'Meu lugar favorito é perto de você.', 'Sempre foi, sem você saber.']]
  ];
  const firstLines = tracks[0][5];
  return `<section class="lyrics-experience" aria-label="Mensagens que acompanham as músicas"><div class="lyrics-stage"><span class="lyrics-kicker">mensagens que eu escrevi para você</span><p class="lyric-previous">${firstLines[0]}</p><h3 class="lyric-current">${firstLines[1]}</h3><p class="lyric-next">${firstLines[2]}</p><div class="lyrics-wave" aria-hidden="true"><i></i><i></i><i></i><i></i><i></i><i></i><i></i></div></div><div class="music-list">${tracks.map(([title, artist, file, start, end, captions]) => `<article class="music-player" data-start="${start}" data-end="${end}" data-captions="${encodeURIComponent(JSON.stringify(captions))}"><audio preload="none" src="${file}"></audio><div class="music-top"><button class="music-play-button" type="button" aria-label="Tocar trecho de ${title}">▶</button><div><strong>${title}</strong><small>${artist}</small></div><span class="music-time">0:00 / 0:00</span></div><div class="music-progress"><span></span></div><p class="music-caption">${captions[1]}</p></article>`).join('')}</div></section>`;
}

function renderMediaSection() {
  return `<section class="illustration-moment" aria-label="Um retrato ilustrado de vocês"><img src="assets/illustrations/couple-bouquet-sticker-personal.png" alt="Ilustração de vocês dois trocando flores" /><div><span class="eyebrow">um retrato do que eu sinto</span><h3>Você faz meu coração<br />ficar em casa.</h3><p>Não precisa de foto perfeita quando o que eu sinto por você aparece em cada detalhe.</p></div></section>`;
}

const chapterStickers = {
  portrait: ['assets/stickers/chapter-01-gaming.png', 'Nós dois na primeira partida que mudou tudo'],
  timeline: ['assets/stickers/chapter-02-calls.png', 'Nós dois em uma call na madrugada'],
  details: ['assets/stickers/chapter-03-details.png', 'Nós dois com ursinho e os bichos que lembram Maria'],
  nights: ['assets/stickers/chapter-04-nights.png', 'Nós dois jogando juntos nas nossas noites'],
  music: ['assets/stickers/chapter-05-music.png', 'Nós dois ouvindo música juntos'],
  future: ['assets/stickers/chapter-06-sky.png', 'Nós dois olhando o céu cheio de estrelas'],
  letter: ['assets/stickers/chapter-07-flowers.png', 'Nós dois com um buquê de flores']
};

function renderChapterSticker(type) {
  const [source, alt] = chapterStickers[type] || [];
  return source ? `<figure class="chapter-sticker"><img src="${source}" alt="${alt}" /></figure>` : '';
}

export function activityFor(chapterIndex) {
  const activities = [
    `<section class="moment-selector chapter-activity" aria-labelledby="moment-title"><div><span class="eyebrow">na primeira madrugada</span><h3 id="moment-title">O que fez uma<br /><em>partida ficar?</em></h3></div><div class="moment-options"><button type="button" data-moment="care">A conversa</button><button type="button" data-moment="smile">O convite</button><button type="button" data-moment="remember">O acaso</button></div><p class="moment-answer" id="moment-answer" aria-live="polite">Escolhe uma pista para revisitar o início de nós.</p></section>`,
    `<section class="reasons-section chapter-activity" aria-labelledby="reasons-title"><div class="section-heading"><span id="reasons-title">O que me fez ficar</span><small>coisas que foram crescendo</small></div><div class="reasons-wall"><button type="button" class="reason-note" data-reason="Sua risada fez até as partidas mais comuns parecerem especiais.">sua risada</button><button type="button" class="reason-note" data-reason="Suas conversas fizeram uma simples call virar o lugar em que eu queria estar.">suas conversas</button><button type="button" class="reason-note" data-reason="Sua intensidade me mostrou que tudo em você é vivido de verdade.">sua intensidade</button><button type="button" class="reason-note" data-reason="Sua autenticidade foi o que fez eu querer conhecer cada vez mais de você.">sua autenticidade</button></div><p class="reason-reveal" id="reason-reveal" aria-live="polite">Começa pelo detalhe que mais parece você.</p></section>`,
    `<section class="memory-collection chapter-activity" aria-labelledby="collection-title"><div class="collection-copy"><span class="eyebrow">o universo da maria</span><h3 id="collection-title">Coisas que têm<br /><em>o seu nome.</em></h3><p>Abre um detalhe de cada vez. São pequenas pistas da pessoa que eu amo conhecer.</p></div><div class="collection-tokens" role="group" aria-label="Detalhes que lembram Maria"><button type="button" class="collection-token" data-collection="Ursinhos. Tem um lado seu que dá vontade de proteger e guardar bem pertinho."><span>🧸</span><small>ursinhos</small></button><button type="button" class="collection-token" data-collection="Gatos, Golden e Doberman. Eu gosto de como você fala dos bichos com tanto carinho."><span>🐾</span><small>seus bichos</small></button><button type="button" class="collection-token" data-collection="Senhor dos Anéis. Seu jeito de se encantar por histórias me faz querer ouvir todas as suas favoritas."><span>✦</span><small>suas histórias</small></button><button type="button" class="collection-token" data-collection="Sushi, pizza, hambúrguer e doce. Um dia eu quero uma noite simples escolhendo tudo isso com você."><span>♡</span><small>seu pedido</small></button></div><p class="collection-reveal" id="collection-reveal" aria-live="polite">Escolhe uma coisa que parece muito Maria.</p></section>`,
    `<section class="heart-game chapter-activity" aria-labelledby="heart-game-title"><div class="heart-game-intro"><span class="eyebrow">missão das nossas noites</span><h3 id="heart-game-title">Colecione<br /><em>nossos corações.</em></h3><p>Como nas noites de GTA e em cada call, a missão é uma só: ficar por perto até o fim.</p><button class="game-start" id="heart-game-start" type="button">Começar a missão <span>♡</span></button></div><div class="heart-playground" id="heart-playground" aria-label="Área do jogo" aria-live="polite"><span class="game-placeholder">pronta para a missão?</span><span class="heart-score" id="heart-score">0 / 10</span></div><p class="heart-game-message" id="heart-game-message" aria-live="polite">Cada coração é uma lembrança das noites que fizeram a gente se aproximar.</p></section>`,
    `<section class="music-bridge chapter-activity"><span class="eyebrow">a trilha dos quatro meses</span><p>Tem música que toca e acaba. Essas ficaram porque agora carregam uma parte de você e de tudo o que a gente viveu.</p></section>`,
    `<section class="midnight-sky chapter-activity" aria-labelledby="sky-title"><div class="sky-copy"><span class="eyebrow">depois de quatro meses</span><h3 id="sky-title">Um céu inteiro<br /><em>para nós.</em></h3><p>Cada estrela guarda uma parte do futuro que eu ainda quero viver com você.</p></div><div class="constellation" role="group" aria-label="Estrelas com mensagens"><button type="button" class="sky-star star-one" data-star="Eu ainda acho muito bonito que tudo tenha começado em uma madrugada qualquer."><span>✦</span><i aria-hidden="true"></i></button><button type="button" class="sky-star star-two" data-star="Se eu pudesse escolher uma companhia para todas as minhas noites, seria você."><span>✦</span><i aria-hidden="true"></i></button><button type="button" class="sky-star star-three" data-star="Mesmo longe, você sempre encontra um jeito de ficar perto de mim."><span>✦</span><i aria-hidden="true"></i></button><button type="button" class="sky-star star-four" data-star="Quatro meses me mostraram que algumas histórias começam devagar e acabam virando casa."><span>✦</span><i aria-hidden="true"></i></button><button type="button" class="sky-star star-five" data-star="Em todas as versões do meu futuro, eu espero encontrar você sorrindo nele."><span>✦</span><i aria-hidden="true"></i></button><button type="button" class="sky-star star-six" data-star="Você é uma razão para eu acreditar em coisas bonitas acontecendo por acaso."><span>✦</span><i aria-hidden="true"></i></button></div><p class="sky-reveal" id="sky-reveal" aria-live="polite">Escolhe uma estrela e descobre o que eu desejo para nós.</p></section>`,
    `<section class="letters-section chapter-activity" aria-labelledby="letters-title"><div class="section-heading"><span id="letters-title">Cartinhas para você</span><small>para o fim da nossa história, por enquanto</small></div><div class="sealed-letters animated-letters"><article><button type="button" class="sealed-letter" data-letter="Você é muito maior do que qualquer dúvida que aparecer. Seu jeito é raro, bonito e merece ser amado exatamente como é."><span class="letter-flap">♡</span><span class="letter-label">Quando você duvidar de si</span><i aria-hidden="true">para maria</i></button></article><article><button type="button" class="sealed-letter" data-letter="Mesmo quando não estamos no mesmo lugar, tem um pedaço meu contando as horas para te encontrar de novo em alguma call."><span class="letter-flap">✦</span><span class="letter-label">Quando der saudade</span><i aria-hidden="true">com carinho</i></button></article><article><button type="button" class="sealed-letter" data-letter="Tudo começou por acaso às 03:32. E eu ainda acho bonito demais pensar que você foi a pessoa que caiu naquela mesma partida."><span class="letter-flap">01.05</span><span class="letter-label">Quando quiser lembrar de nós</span><i aria-hidden="true">nossa história</i></button></article></div><p class="letter-reveal" id="letter-reveal" aria-live="polite">Escolha uma carta para abrir.</p></section>`
  ];
  return activities[chapterIndex] || '';
}

function renderCards(chapter) {
  const cards = chapter.cards.map(([title, text], index) => `<article class="memory-card memory-slide ${chapter.type === 'music' ? 'song-card' : ''}"><span class="memory-date">fragmento ${String(index + 1).padStart(2, '0')}</span><h4>${title}</h4><p class="${index === 1 && chapter.type === 'portrait' ? 'quote' : ''}">${text}</p>${chapter.type === 'audio' ? `<div class="audio-player" data-id="audio-${index}"><button class="play-button" aria-label="Reproduzir áudio">▶</button><div class="audio-info"><strong>Mensagem ${index + 1}</strong><div class="mini-progress"><span></span></div></div><span class="audio-time">0:18</span></div>` : ''}</article>`).join('');
  const carousel = `<section class="memory-carousel" aria-label="Fragmentos desta lembrança"><div class="carousel-rail">${cards}</div><div class="carousel-controls"><button type="button" data-carousel="previous" aria-label="Fragmento anterior">←</button><span class="carousel-count" aria-live="polite"></span><button type="button" data-carousel="next" aria-label="Próximo fragmento">→</button></div></section>`;
  return `${renderChapterSticker(chapter.type)}${carousel}`;
}

export function contentFor(chapter) {
  if (chapter.type === 'gallery') return renderGallery();
  if (chapter.type === 'music') return `${renderChapterSticker(chapter.type)}${renderMusic()}`;
  if (chapter.type === 'letter') return `${renderChapterSticker(chapter.type)}<article class="letter"><p>Maria, quatro meses atrás eu entrei em uma partida sem imaginar que aquela madrugada às 03:32 ia trazer você para a minha vida. Você puxando assunto, eu mais quieto e uma conversa completamente aleatória. Foi assim que tudo começou, e eu acho bonito demais pensar nisso.</p><p>Depois vieram os jogos, os convites, as calls e a vontade de repetir tudo no dia seguinte. Aos poucos, você deixou de ser uma pessoa com quem eu jogava e virou alguém que eu queria ter por perto em qualquer momento.</p><p>Eu penso em você no trabalho, espero a hora de ligar o computador e gosto de cada conversa que a gente consegue ter. Não é sobre o jogo. É sobre você, sobre ouvir sua voz, ver suas reações e sentir que, mesmo de longe, a gente encontra um jeito de ficar junto.</p><p>Eu amo seu jeito de ser, suas frases, sua risada, sua intensidade e até as coisas que você faz sem perceber. Você é única para mim, Maria.</p><p>Eu te amo muito. Quero continuar vivendo mais histórias, mais noites e mais versões de nós. Quero cuidar do que estamos construindo e escolher você em cada passo que vier.</p><p class="final-line">Obrigado por ter me chamado para jogar naquele dia. Ainda bem que foi você. Ainda bem que somos nós.</p></article>`;
  return renderCards(chapter);
}
