export const chapters = [
  { title: '01/05/2026', subtitle: '03:32', intro: '01 de maio, 03:32. Era pra ser só uma partida aleatória de Valorant.', type: 'portrait', cards: [
    ['A conversa mais aleatória possível', 'Eu tava quieto, na minha. Você tava fazendo o squad inteiro conversar. Do nada o assunto virou Caim, Abel e perguntas da Bíblia que você nem sabia responder direito. Eu achei engraçado demais.'], ['Aquele primeiro convite', 'Depois você me adicionou e me chamou pra jogar. Aí chamou de novo. E depois disso a gente simplesmente não parou mais.'], ['Ainda bem que foi você', 'Eu não tava procurando nada naquela partida. Só dei sorte de cair na mesma fila que você.'] ] },
  { title: 'Como tudo aconteceu?', subtitle: 'Foi tão bom!', intro: 'Não foi de uma vez. Foi jogo depois de jogo, call depois de call, até você virar parte dos meus dias.', type: 'timeline', cards: [
    ['No começo era só Valorant', 'Uma madrugada qualquer, uma menina muito extrovertida e eu tentando acompanhar as conversas que você puxava com todo mundo.'], ['Quando eu quis ficar por perto', 'Você passou por uma fase pesada. Eu queria te ajudar, te ouvir e deixar as coisas um pouco menos difíceis.'], ['Quando eu entendi', 'Eu percebi no trabalho, pensando em você e contando as horas pra ligar o PC. Só que não era pelo jogo. Era porque eu queria ficar com você.'] ] },
  { title: 'Coisas que são sua cara', subtitle: 'As que eu fui guardando', intro: 'Não tem como colocar você inteira num site. Mas tem umas coisas que, quando eu vejo, lembram você na hora.', type: 'details', cards: [
    ['26 de outubro', 'O dia da Maria. E de um monte de gente que ainda nem imagina a sorte que tem de te conhecer.'], ['O seu jeitinho', 'Você começa falando de uma coisa, pula pra outra e, no fim, até o assunto mais aleatório fica bom. É muito você.'], ['As suas frases', '“Quem pode, pode. Quem não pode, se sacode.” E a melhor: “Não é Maria que vai com os outros, são os outros que vão com Maria.”'], ['Seu kit oficial', 'Ursinhos de pelúcia, gatos, Golden Retriever, Doberman e Senhor dos Anéis. Não tinha como não ter isso aqui.'], ['O que pediria pra você', 'Sushi, hambúrguer com cheddar e bacon, x-bacon, empadão, cachorro-quente ou pizza de frango com catupiry. Depois a gente resolve com Milka, Kinder Bueno, milk-shake de Nutella, fondant, palha italiana ou brownie.'], ['E é isso que me pega', 'O seu sorriso, seus olhos, seu cabelo. Seu jeito de rir, de reagir, de brigar e de fazer qualquer coisa virar uma onda.'] ] },
  { title: 'Nossas noites', subtitle: 'GTA, call e você', intro: 'Teve uma semana que GTA Online virou muito mais que GTA Online. Eu lembro dela até hoje.', type: 'nights', cards: [['Uma semana que ficou', 'A gente jogou tanto, riu tanto e ficou tanto em call que, sem perceber, foi criando um carinho muito grande ali.'], ['O primeiro “mô”', 'Foi no meio das calls que o “mô” apareceu. Depois veio a primeira vez dormindo junto em call. Pequenas coisas que pra mim não foram pequenas.'], ['Os nossos “eu te amo”', 'Eu lembro do meu primeiro “eu te amo”. E lembro do seu também. Não sei explicar, só sei que ficou guardado aqui.']] },
  { title: 'Músicas que são você', subtitle: 'Só de tocar eu lembro', intro: 'Essas músicas têm você no meio delas. Algumas porque você escolheu, outras porque agora eu não consigo ouvir sem pensar em você.', type: 'music', cards: [['As que você escolheu', 'TE ENCONTRAR · MODÉSTIA PARTE\nORIENTE\nREBECA - LINDA, LOUCA E MIMADA'], ['As que me levam pra você', 'Like I Want You - Giveon\nTá vendo aquela lua que brilha lá no céu\nMeu Abrigo - Melim']] },
  { title: 'O que eu quero viver', subtitle: 'Daqui pra frente', intro: 'Eu não preciso apressar nada. Só quero continuar conhecendo você e vivendo tudo que ainda tem pra gente viver.', type: 'future', cards: [['Do jeito que tá sendo', 'Eu gosto das nossas conversas, dos desabafos, das zoeiras e até dos momentos em silêncio. Gosto de fazer parte do seu dia.'], ['Mais noites assim', 'Quero mais calls, mais jogos, mais “môs” e mais noites em que o melhor plano é só ficar junto.']] },
  { title: 'Pra você', subtitle: 'O que eu queria te falar', intro: 'Guardei isso pro final porque eu queria que você entendesse de onde isso tudo veio.', type: 'letter', cards: [] }
];

function renderGallery() {
  return `<div class="gallery">${[['01','#e6b6b0','m','uma tarde bonita','-3deg'],['02','#c6adb2','M','entre risos','2deg'],['03','#dec4aa','✦','luz dourada','-1deg'],['04','#b7c7bf','m','sem pressa','3deg'],['05','#d4bbc4','♡','só nós','-2deg'],['06','#aebecb','M','um lugar feliz','2deg']].map(([id,tone,mark,title,tilt]) => `<button class="polaroid" style="--tone:${tone};--tilt:${tilt}" data-id="${id}" data-tone="${tone}" data-mark="${mark}" data-title="${title}" data-caption="Uma lembrança feita de detalhes — e de tudo aquilo que não precisa ser explicado."><div class="photo-art"><span>${mark}</span></div><small>${title}</small></button>`).join('')}</div>`;
}

function renderMusic() {
  const tracks = [
    ['Te Encontrar', 'Modéstia Parte', 'assets/audio/te-encontrar.mp3', 56, 86, ['Quando essa música começa,', 'eu lembro que tudo ficou mais bonito', 'depois que encontrei você.', 'E de como eu só queria te encontrar.']],
    ['Linda, Louca e Mimada', 'Oriente', 'assets/audio/linda-louca-e-mimada.mp3', 72, 102, ['Você faz tudo do seu jeito.', 'Ninguém tem a sua energia.', 'E talvez seja exatamente por isso', 'que eu gosto tanto de você.']],
    ['Like I Want You', 'Giveon', 'assets/audio/like-i-want-you.mp3', 69, 99, ['Tem coisa que eu tento disfarçar.', 'Eu finjo que não penso tanto.', 'Mas o meu coração sempre entrega', 'quando o assunto é você.']],
    ['Pupila', 'ANAVITÓRIA e Vitor Kley', 'assets/audio/pupila.mp3', 60, 90, ['Você aparece nos meus pensamentos.', 'No meio de qualquer dia comum.', 'E eu gosto até das partes do dia', 'em que eu paro só para lembrar de você.']],
    ['Meu Abrigo', 'Melim', 'assets/audio/meu-abrigo.mp3', 81, 111, ['Você é meu lugar de paz.', 'A minha escolha em dias leves e difíceis.', 'Meu lugar favorito é perto de você.', 'Sempre foi, sem você saber.']]
  ];
  const firstLines = tracks[0][5];
  return `<section class="lyrics-experience" aria-label="Mensagens que acompanham as músicas"><div class="lyrics-stage"><span class="lyrics-kicker">mensagens que eu escrevi para você</span><p class="lyric-previous">${firstLines[0]}</p><h3 class="lyric-current">${firstLines[1]}</h3><p class="lyric-next">${firstLines[2]}</p><div class="lyrics-wave" aria-hidden="true"><i></i><i></i><i></i><i></i><i></i><i></i><i></i></div></div><div class="music-list">${tracks.map(([title, artist, file, start, end, captions]) => `<article class="music-player" data-start="${start}" data-end="${end}" data-captions="${encodeURIComponent(JSON.stringify(captions))}"><audio preload="none" src="${file}"></audio><div class="music-top"><button class="music-play-button" type="button" aria-label="Tocar trecho de ${title}">▶</button><div><strong>${title}</strong><small>${artist}</small></div><span class="music-time">0:00 / 0:00</span></div><div class="music-progress"><span></span></div><p class="music-caption">${captions[1]}</p></article>`).join('')}</div></section>`;
}

function renderMediaSection() {
  return `<section class="illustration-moment" aria-label="Um retrato ilustrado de vocês"><img src="assets/illustrations/couple-bouquet-sticker-personal.png" alt="Ilustração de vocês dois trocando flores" /><div><span class="eyebrow">um retrato do que eu sinto</span><h3>Você faz meu coração<br />ficar em casa.</h3><p>Não precisa de foto perfeita quando o que eu sinto por você aparece em cada detalhe.</p></div></section>`;
}

export function activityFor(chapterIndex) {
  const activities = [
    `<section class="moment-selector chapter-activity" aria-labelledby="moment-title"><div><span class="eyebrow">antes da próxima cena</span><h3 id="moment-title">O que essa noite<br /><em>deixou em você?</em></h3></div><div class="moment-options"><button type="button" data-moment="care">Um carinho</button><button type="button" data-moment="smile">Um sorriso</button><button type="button" data-moment="remember">Lembrar de nós</button></div><p class="moment-answer" id="moment-answer" aria-live="polite">Escolhe uma das opções. Eu deixei uma coisinha em cada uma.</p></section>`,
    `<section class="reasons-section chapter-activity" aria-labelledby="reasons-title"><div class="section-heading"><span id="reasons-title">Coisas que foram ficando</span><small>toque em cada uma</small></div><div class="reasons-wall"><button type="button" class="reason-note" data-reason="Sua risada faz qualquer momento ficar melhor.">sua risada</button><button type="button" class="reason-note" data-reason="Seu jeito de falar de mil assuntos deixa tudo mais divertido.">suas conversas</button><button type="button" class="reason-note" data-reason="Você tem um jeito bonito de ser intensa e verdadeira.">sua intensidade</button><button type="button" class="reason-note" data-reason="Você é você, e isso já é mais do que suficiente.">sua autenticidade</button></div><p class="reason-reveal" id="reason-reveal" aria-live="polite">Começa por qualquer um.</p></section>`,
    `<section class="love-garden chapter-activity" aria-labelledby="garden-title"><div class="garden-copy"><span class="eyebrow">coisas que são sua cara</span><h3 id="garden-title">Cultive um<br /><em>carinho.</em></h3><p>Escolhe uma flor. Em cada uma eu escondi uma coisa que queria te dizer.</p></div><div class="garden-bed" role="group" aria-label="Flores com mensagens"><button type="button" class="garden-flower flower-pink" data-garden="Você deixa os meus dias mais coloridos sem nem perceber."><span>✿</span><small>leveza</small></button><button type="button" class="garden-flower flower-yellow" data-garden="O seu jeitinho é uma das coisas mais lindas que eu tive a sorte de conhecer."><span>✿</span><small>jeitinho</small></button><button type="button" class="garden-flower flower-lilac" data-garden="Eu gosto de nós nas piadas, nas calls e nos silêncios."><span>✿</span><small>nós</small></button><button type="button" class="garden-flower flower-red" data-garden="Se eu pudesse escolher uma flor para guardar, ela teria o seu nome."><span>♥</span><small>maria</small></button></div><p class="garden-reveal" id="garden-reveal" aria-live="polite">Uma flor está esperando você.</p></section>`,
    `<section class="heart-game chapter-activity" aria-labelledby="heart-game-title"><div class="heart-game-intro"><span class="eyebrow">um intervalo entre nós</span><h3 id="heart-game-title">Colecione<br /><em>nossos corações.</em></h3><p>Clique nos corações antes que eles sumam. Dez deles guardam uma surpresa.</p><button class="game-start" id="heart-game-start" type="button">Começar o jogo <span>♡</span></button></div><div class="heart-playground" id="heart-playground" aria-label="Área do jogo" aria-live="polite"><span class="game-placeholder">pronta para brincar?</span><span class="heart-score" id="heart-score">0 / 10</span></div><p class="heart-game-message" id="heart-game-message" aria-live="polite">Cada coração é só uma desculpa para te mandar mais carinho.</p></section>`,
    `<section class="music-bridge chapter-activity"><span class="eyebrow">uma pausa para sentir</span><p>Algumas músicas não explicam tudo. Mas deixam um pedacinho do que eu sinto tocar por nós.</p></section>`,
    `<section class="midnight-sky chapter-activity" aria-labelledby="sky-title"><div class="sky-copy"><span class="eyebrow">para as nossas madrugadas</span><h3 id="sky-title">Um céu inteiro<br /><em>para você.</em></h3><p>Tem estrela que parece só um ponto de luz. Até você tocar nela.</p></div><div class="constellation" role="group" aria-label="Estrelas com mensagens"><button type="button" class="sky-star star-one" data-star="Eu ainda acho muito bonito que tudo tenha começado em uma madrugada qualquer."><span>✦</span><i aria-hidden="true"></i></button><button type="button" class="sky-star star-two" data-star="Se eu pudesse escolher uma companhia para todas as minhas noites, seria você."><span>✦</span><i aria-hidden="true"></i></button><button type="button" class="sky-star star-three" data-star="Mesmo longe, você sempre encontra um jeito de ficar perto de mim."><span>✦</span><i aria-hidden="true"></i></button><button type="button" class="sky-star star-four" data-star="Eu gosto de pensar que histórias começam devagar e acabam virando casa."><span>✦</span><i aria-hidden="true"></i></button><button type="button" class="sky-star star-five" data-star="Em todas as versões do meu futuro, eu espero encontrar você sorrindo nele."><span>✦</span><i aria-hidden="true"></i></button><button type="button" class="sky-star star-six" data-star="Você é uma razão para eu acreditar em coisas bonitas acontecendo por acaso."><span>✦</span><i aria-hidden="true"></i></button></div><p class="sky-reveal" id="sky-reveal" aria-live="polite">Escolhe uma estrela e faz um pedido.</p></section>`,
    `<section class="letters-section chapter-activity" aria-labelledby="letters-title"><div class="section-heading"><span id="letters-title">Cartinhas para você</span><small>para o fim da nossa história — por enquanto</small></div><div class="sealed-letters animated-letters"><article><button type="button" class="sealed-letter" data-letter="Você é muito maior do que qualquer dúvida que aparecer. Seu jeito é raro, bonito e merece ser amado exatamente como é."><span class="letter-flap">♡</span><span class="letter-label">Quando você duvidar de si</span><i aria-hidden="true">para maria</i></button></article><article><button type="button" class="sealed-letter" data-letter="Mesmo quando não estamos no mesmo lugar, tem um pedaço meu contando as horas para te encontrar de novo em alguma call."><span class="letter-flap">✦</span><span class="letter-label">Quando der saudade</span><i aria-hidden="true">com carinho</i></button></article><article><button type="button" class="sealed-letter" data-letter="Tudo começou por acaso às 03:32. E eu ainda acho bonito demais pensar que você foi a pessoa que caiu naquela mesma partida."><span class="letter-flap">01.05</span><span class="letter-label">Quando quiser lembrar de nós</span><i aria-hidden="true">nossa história</i></button></article></div><p class="letter-reveal" id="letter-reveal" aria-live="polite">Escolha uma carta para abrir.</p></section>`
  ];
  return activities[chapterIndex] || '';
}

function renderCards(chapter) {
  const cards = chapter.cards.map(([title, text], index) => `<article class="memory-card memory-slide ${chapter.type === 'music' ? 'song-card' : ''}"><span class="memory-date">fragmento ${String(index + 1).padStart(2, '0')}</span><h4>${title}</h4><p class="${index === 1 && chapter.type === 'portrait' ? 'quote' : ''}">${text}</p>${chapter.type === 'audio' ? `<div class="audio-player" data-id="audio-${index}"><button class="play-button" aria-label="Reproduzir áudio">▶</button><div class="audio-info"><strong>Mensagem ${index + 1}</strong><div class="mini-progress"><span></span></div></div><span class="audio-time">0:18</span></div>` : ''}</article>`).join('');
  const carousel = `<section class="memory-carousel" aria-label="Fragmentos desta lembrança"><div class="carousel-rail">${cards}</div><div class="carousel-controls"><button type="button" data-carousel="previous" aria-label="Fragmento anterior">←</button><span class="carousel-count" aria-live="polite"></span><button type="button" data-carousel="next" aria-label="Próximo fragmento">→</button></div></section>`;
  return `${chapter.type === 'details' ? renderMediaSection() : ''}${carousel}`;
}

export function contentFor(chapter) {
  if (chapter.type === 'gallery') return renderGallery();
  if (chapter.type === 'music') return renderMusic();
  if (chapter.type === 'letter') return `<article class="letter"><p>Maria, eu fico pensando em como tudo começou. Uma partida aleatória às 03:32, você puxando assunto com todo mundo e eu mais quieto. Se alguém me contasse que aquela noite ia trazer você pra minha vida, eu não ia acreditar.</p><p>Hoje eu penso em você no meio do trabalho. Espero a hora de ligar o PC. E eu sei que não é por causa do jogo. É porque eu quero te ver, conversar com você e só ficar perto, mesmo que seja em call.</p><p>Eu amo o seu jeito, suas frases, sua risada, suas reações e até as coisas que você faz e nem percebe. Você é muito única pra mim.</p><p>Eu te amo muito.</p><p>Quero que você seja minha mulher, minha namorada, minha esposa. Quero você comigo em tudo que der. Quero ficar do seu lado pra sempre, se for possível.</p><p class="final-line">Obrigado por ter me chamado pra jogar naquele dia. Ainda bem que você chamou.</p></article>`;
  return renderCards(chapter);
}
