export const chapters = [
  { title: '01/05/2026', subtitle: '03:32', intro: '01 de maio, 03:32. Era pra ser só uma partida aleatória de Valorant.', type: 'portrait', cards: [
    ['A conversa mais aleatória possível', 'Eu tava quieto, na minha. Você tava fazendo o squad inteiro conversar. Do nada o assunto virou Caim, Abel e perguntas da Bíblia que você nem sabia responder direito. Eu achei engraçado demais.'], ['Aquele primeiro convite', 'Depois você me adicionou e me chamou pra jogar. Aí chamou de novo. E depois disso a gente simplesmente não parou mais.'], ['Ainda bem que foi você', 'Eu não tava procurando nada naquela partida. Só dei sorte de cair na mesma fila que você.'] ] },
  { title: 'Como tudo aconteceu?', subtitle: 'Foi tão bom!', intro: 'Não foi de uma vez. Foi jogo depois de jogo, call depois de call, até você virar parte dos meus dias.', type: 'timeline', cards: [
    ['No começo era só Valorant', 'Uma madrugada qualquer, uma menina muito extrovertida e eu tentando acompanhar as conversas que você puxava com todo mundo.'], ['Quando eu quis ficar por perto', 'Você passou por uma fase pesada. Eu queria te ajudar, te ouvir e deixar as coisas um pouco menos difíceis.'], ['Quando eu entendi', 'Eu percebi no trabalho, pensando em você e contando as horas pra ligar o PC. Só que não era pelo jogo. Era porque eu queria ficar com você.'] ] },
  { title: 'Coisas que são sua cara', subtitle: 'As que eu fui guardando', intro: 'Não tem como colocar você inteira num site. Mas tem umas coisas que, quando eu vejo, lembram você na hora.', type: 'details', cards: [
    ['26 de outubro', 'O dia da Maria. E de um monte de gente que ainda nem imagina a sorte que tem de te conhecer.'], ['O seu jeitinho', 'Você começa falando de uma coisa, pula pra outra e, no fim, até o assunto mais aleatório fica bom. É muito você.'], ['As suas frases', '“Quem pode, pode. Quem não pode, se sacode.” E a melhor: “Não é Maria que vai com os outros, são os outros que vão com Maria.”'], ['Seu kit oficial', 'Ursinhos de pelúcia, gatos, Golden Retriever, Doberman e Senhor dos Anéis. Não tinha como não ter isso aqui.'], ['O que pediria pra você', 'Sushi, hambúrguer com cheddar e bacon, x-bacon, empadão, cachorro-quente ou pizza de frango com catupiry. Depois a gente resolve com Milka, Kinder Bueno, milk-shake de Nutella, fondant, palha italiana ou brownie.'], ['E é isso que me pega', 'O seu sorriso, seus olhos, seu cabelo. Seu jeito de rir, de reagir, de brigar e de fazer qualquer coisa virar uma onda.'] ] },
  { title: 'Nossas noites', subtitle: 'GTA, call e você', intro: 'Teve uma semana que GTA Online virou muito mais que GTA Online. Eu lembro dela até hoje.', type: 'nights', cards: [['Uma semana que ficou', 'A gente jogou tanto, riu tanto e ficou tanto em call que, sem perceber, foi criando um carinho muito grande ali.'], ['O primeiro “mô”', 'Foi no meio das calls que o “mô” apareceu. Depois veio a primeira vez dormindo junto em call. Pequenas coisas que pra mim não foram pequenas.'], ['Os nossos “eu te amo”', 'Eu lembro do meu primeiro “eu te amo”. E lembro do seu também. Não sei explicar, só sei que ficou guardado aqui.']] },
  { title: 'Músicas que são você', subtitle: 'Só de tocar eu lembro', intro: 'Essas músicas têm você no meio delas. Algumas porque você escolheu, outras porque agora eu não consigo ouvir sem pensar em você.', type: 'music', cards: [['As que você escolheu', 'TE ENCONTRAR · MODÉSTIA PARTE\nORIENTE\nREBECA - LINDA, LOUCA E MIMADA'], ['As que me levam pra você', 'Like I Want You - Giveon\nTá vendo aquela lua que brilha lá no céu\nCuidado - Gaab\nMeu Abrigo - Melim']] },
  { title: 'O que eu quero viver', subtitle: 'Daqui pra frente', intro: 'Eu não preciso apressar nada. Só quero continuar conhecendo você e vivendo tudo que ainda tem pra gente viver.', type: 'future', cards: [['Do jeito que tá sendo', 'Eu gosto das nossas conversas, dos desabafos, das zoeiras e até dos momentos em silêncio. Gosto de fazer parte do seu dia.'], ['Mais noites assim', 'Quero mais calls, mais jogos, mais “môs” e mais noites em que o melhor plano é só ficar junto.']] },
  { title: 'Pra você', subtitle: 'O que eu queria te falar', intro: 'Guardei isso pro final porque eu queria que você entendesse de onde isso tudo veio.', type: 'letter', cards: [] }
];

function renderGallery() {
  return `<div class="gallery">${[['01','#e6b6b0','m','uma tarde bonita','-3deg'],['02','#c6adb2','M','entre risos','2deg'],['03','#dec4aa','✦','luz dourada','-1deg'],['04','#b7c7bf','m','sem pressa','3deg'],['05','#d4bbc4','♡','só nós','-2deg'],['06','#aebecb','M','um lugar feliz','2deg']].map(([id,tone,mark,title,tilt]) => `<button class="polaroid" style="--tone:${tone};--tilt:${tilt}" data-id="${id}" data-tone="${tone}" data-mark="${mark}" data-title="${title}" data-caption="Uma lembrança feita de detalhes — e de tudo aquilo que não precisa ser explicado."><div class="photo-art"><span>${mark}</span></div><small>${title}</small></button>`).join('')}</div>`;
}

function renderMusic() {
  const tracks = [
    ['Te Encontrar', 'Modéstia Parte', 'assets/audio/te-encontrar.mp3', 56, 68, ['Você chegou e combinou comigo.', 'E eu só queria te encontrar.']],
    ['Linda, Louca e Mimada', 'Oriente', 'assets/audio/linda-louca-e-mimada.mp3', 72, 84, ['Você faz tudo do seu jeito.', 'E é por isso que ninguém te esquece.']],
    ['Like I Want You', 'Giveon', 'assets/audio/like-i-want-you.mp3', 69, 81, ['Tem coisa que a gente tenta esconder.', 'Mas o coração entrega.']],
    ['Pupila', 'ANAVITÓRIA e Vitor Kley', 'assets/audio/pupila.mp3', 60, 72, ['Você ocupa meus pensamentos.', 'E eu gosto até do jeito que você existe.']],
    ['Cuidado', 'Gaab', 'assets/audio/cuidado.mp3', 64, 76, ['Você merece alguém que te admire.', 'Que fique do seu lado sem complicar.']],
    ['Meu Abrigo', 'Melim', 'assets/audio/meu-abrigo.mp3', 81, 93, ['Você é meu lugar de paz.', 'Meu lugar favorito é perto de você.']]
  ];
  return `<div class="music-list">${tracks.map(([title, artist, file, start, end, captions]) => `<article class="music-player" data-start="${start}" data-end="${end}" data-captions="${encodeURIComponent(JSON.stringify(captions))}"><audio preload="none" src="${file}"></audio><div class="music-top"><button class="music-play-button" type="button" aria-label="Tocar trecho de ${title}">▶</button><div><strong>${title}</strong><small>${artist}</small></div><span class="music-time">0:00 / 0:00</span></div><div class="music-progress"><span></span></div><p class="music-caption">${captions[0]}</p></article>`).join('')}</div>`;
}

function renderMediaSection() {
  return `<section class="illustration-moment" aria-label="Um retrato ilustrado de vocês"><img src="assets/illustrations/couple-bouquet-sticker-personal.png" alt="Ilustração de vocês dois trocando flores" /><div><span class="eyebrow">um retrato do que eu sinto</span><h3>Você faz meu coração<br />ficar em casa.</h3><p>Não precisa de foto perfeita quando o que eu sinto por você aparece em cada detalhe.</p></div></section>`;
}

function renderCards(chapter) {
  const cards = chapter.cards.map(([title, text], index) => `<article class="memory-card memory-slide ${chapter.type === 'music' ? 'song-card' : ''}"><span class="memory-date">fragmento ${String(index + 1).padStart(2, '0')}</span><h4>${title}</h4><p class="${index === 1 && chapter.type === 'portrait' ? 'quote' : ''}">${text}</p>${chapter.type === 'audio' ? `<div class="audio-player" data-id="audio-${index}"><button class="play-button" aria-label="Reproduzir áudio">▶</button><div class="audio-info"><strong>Mensagem ${index + 1}</strong><div class="mini-progress"><span></span></div></div><span class="audio-time">0:18</span></div>` : ''}</article>`).join('');
  const carousel = `<section class="memory-carousel" aria-label="Fragmentos desta lembrança"><div class="carousel-rail">${cards}</div><div class="carousel-controls"><button type="button" data-carousel="previous" aria-label="Fragmento anterior">←</button><span class="carousel-count" aria-live="polite"></span><button type="button" data-carousel="next" aria-label="Próximo fragmento">→</button></div></section>`;
  return `${chapter.type === 'details' ? renderMediaSection() : ''}${carousel}`;
}

export function contentFor(chapter) {
  if (chapter.type === 'gallery') return renderGallery();
  if (chapter.type === 'music') return renderMusic();
  if (chapter.type === 'letter') return `<article class="letter"><p>Maria, eu fico pensando em como tudo começou. Uma partida aleatória às 03:32, você puxando assunto com todo mundo e eu mais quieto. Se alguém me contasse que aquela noite ia trazer você pra minha vida, eu não ia acreditar.</p><p>Hoje eu penso em você no meio do trabalho. Espero a hora de ligar o PC. E eu sei que não é por causa do jogo. É porque eu quero te ver, conversar com você e só ficar perto, mesmo que seja em call.</p><p>Eu amo o seu jeito, suas frases, sua risada, suas reações e até as coisas que você faz e nem percebe. Você é muito única pra mim.</p><p>Eu te amo muito.</p><p>Quero que você seja minha mulher, minha namorada, minha esposa. Quero você comigo em tudo que der. Quero ficar do seu lado pra sempre, se for possível.</p><p class="final-line">Obrigado por ter me chamado pra jogar naquele dia. Ainda bem que você chamou.</p></article>`;
  return renderCards(chapter);
}
